kind: ConfigMap
apiVersion: v1
metadata:
  name: proxy-{{ .Chart.Name }}
  labels:
    proxy: internal
data:
  path: {{ .Values.context }}
  destination: {{ .Chart.Name }}.{{ .Release.Namespace }}:9000/{{ .Chart.Name }}