apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Chart.Name }}-de
    labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: ""
    resources:
        requests:
            storage: {{ .Values.size }}