apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 5432
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}